# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "db/seeds.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"

Style/Documentation:
  Enabled: false

